import argparse
import heapq
import itertools
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import nibabel as nib
import numpy as np
from scipy.ndimage import binary_dilation, center_of_mass, label


# ============================================================
# 1. Global Settings
# ============================================================a
BASE_DIR = Path(r"C:\Users\User\Desktop\AbdVesselGen")
ROI_CT_ROOT = BASE_DIR / "ROI_CT"
ANCHOR_POINTS_ROOT = BASE_DIR / "AnchorPoints"
RESULTS_INTERMEDIATE_ROOT = BASE_DIR / "Results" / "Intermediate"

# Input suffixes
ANCHOR_SPHERES_SUFFIX = "duodenum_surface_anchor_spheres"
ANCHOR_POINTS_TXT_SUFFIX = "anchor_points_from_search_volumes"

# Use only starting points derived from this search volume.
START_VOLUME_NAME = "search3231_volume"

# Output
OUTPUT_FILENAME = "GDA.nii.gz"
SUMMARY_FILENAME = "GDA_path_summary.txt"

# Dijkstra constraints
Y_LIMIT_MAX = 268
INVALID_HU_VALUE = -1024
AVOID_INVALID_HU = True

# Path drawing dilation. Original script used one binary dilation with a 3x3x3 structuring element.
PATH_DILATION_ITERATIONS = 1

# If final output already exists, skip this step.
SKIP_IF_FINAL_EXISTS = True


# ============================================================
# 2. Path Builders
# ============================================================
def build_roi_ct_path(case_id: str) -> Path:
    """
    Kept only for backward compatibility with older versions.
    The current GDA pathfinding uses the original CT passed by run.py instead of ROI_CT.
    """
    return ROI_CT_ROOT / f"{case_id}_ROI_CT.nii.gz"


def build_anchor_spheres_path(case_id: str) -> Path:
    return ANCHOR_POINTS_ROOT / f"{case_id}_{ANCHOR_SPHERES_SUFFIX}.nii.gz"


def build_anchor_points_txt_path(case_id: str) -> Path:
    return ANCHOR_POINTS_ROOT / f"{case_id}_{ANCHOR_POINTS_TXT_SUFFIX}.txt"


def build_output_path(case_id: str) -> Path:
    return RESULTS_INTERMEDIATE_ROOT / f"{case_id}_{OUTPUT_FILENAME}"


def build_summary_path(case_id: str) -> Path:
    return RESULTS_INTERMEDIATE_ROOT / f"{case_id}_{SUMMARY_FILENAME}"


# ============================================================
# 3. Basic Utilities
# ============================================================
def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def strip_nii_extension(filename: str) -> str:
    lower = filename.lower()
    if lower.endswith(".nii.gz"):
        return filename[:-7]
    if lower.endswith(".nii"):
        return filename[:-4]
    return Path(filename).stem


def load_nifti(path: Path):
    if not path.exists():
        raise FileNotFoundError(f"File not found:\n{path}")
    img = nib.load(str(path))
    data = img.get_fdata()
    return img, data


def check_same_shape(reference_name: str, reference_data: np.ndarray, target_name: str, target_data: np.ndarray) -> None:
    if reference_data.shape != target_data.shape:
        raise ValueError(
            f"Shape mismatch: {reference_name} shape {reference_data.shape} "
            f"!= {target_name} shape {target_data.shape}"
        )


def is_inside_shape(point: Tuple[int, int, int], shape: Tuple[int, int, int]) -> bool:
    x, y, z = point
    sx, sy, sz = shape
    return 0 <= x < sx and 0 <= y < sy and 0 <= z < sz


# ============================================================
# 4. Anchor Point TXT Parser
# ============================================================
def parse_anchor_points_txt(txt_path: Path) -> List[Dict]:
    """
    Parse the tab-separated anchor point file generated by
    FindAnchorPointsFromSearchVolumes.py.

    Expected table columns include:
      volume_name, component_id, point_x, point_y, point_z, point_hu
    """
    if not txt_path.exists():
        raise FileNotFoundError(f"Anchor points TXT not found:\n{txt_path}")

    records: List[Dict] = []
    header = None

    with open(txt_path, "r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line:
                continue

            parts = line.split("\t")

            # Metadata rows.
            if len(parts) == 2 and parts[0] in {"case_id", "invalid_hu_value", "max_search_radius"}:
                continue

            if parts[0] == "volume_name":
                header = parts
                continue

            if header is None:
                continue

            if len(parts) != len(header):
                print(f"[WARNING] Skipping malformed TXT row: {line}")
                continue

            row = dict(zip(header, parts))

            try:
                row["component_id"] = int(row["component_id"])
                row["component_voxels"] = int(row["component_voxels"])
                row["centroid_x"] = float(row["centroid_x"])
                row["centroid_y"] = float(row["centroid_y"])
                row["centroid_z"] = float(row["centroid_z"])
                row["point_x"] = int(row["point_x"])
                row["point_y"] = int(row["point_y"])
                row["point_z"] = int(row["point_z"])
                row["point_hu"] = float(row["point_hu"])
                row["distance_to_centroid"] = float(row["distance_to_centroid"])
                row["found_radius"] = int(row["found_radius"])
            except Exception as e:
                print(f"[WARNING] Skipping row because parsing failed: {line}")
                print(f"[WARNING] Error: {e}")
                continue

            records.append(row)

    return records


def get_start_points_from_search3231(anchor_txt_path: Path, ct_data: np.ndarray) -> List[Tuple[int, int, int]]:
    records = parse_anchor_points_txt(anchor_txt_path)
    selected = [r for r in records if r.get("volume_name") == START_VOLUME_NAME]

    if len(selected) == 0:
        raise RuntimeError(
            f"No starting point records found from volume_name={START_VOLUME_NAME} in:\n{anchor_txt_path}"
        )

    starts: List[Tuple[int, int, int]] = []
    seen = set()

    for r in selected:
        point = (int(r["point_x"]), int(r["point_y"]), int(r["point_z"]))
        if point in seen:
            continue
        if not is_inside_shape(point, ct_data.shape):
            print(f"[WARNING] Skipping out-of-bounds start point: {point}")
            continue
        seen.add(point)
        starts.append(point)

    if len(starts) == 0:
        raise RuntimeError("No valid in-bounds search3231 starting point was found.")

    print("=" * 100)
    print("[STARTING POINTS FROM SEARCH3231]")
    for i, p in enumerate(starts, start=1):
        print(f"  Start {i}: {p}, CT HU={float(ct_data[p]):.1f}")
    print("=" * 100)

    return starts


# ============================================================
# 5. Target Anchor Sphere Centroids
# ============================================================
def get_target_points_from_anchor_spheres(anchor_spheres_path: Path, ct_data: np.ndarray) -> List[Tuple[int, int, int]]:
    anchor_img, anchor_data = load_nifti(anchor_spheres_path)
    check_same_shape("ROI CT", ct_data, "anchor spheres", anchor_data)

    labeled_anchors, num_anchors = label(anchor_data > 0)

    if num_anchors == 0:
        raise RuntimeError(f"No anchor sphere component found in: {anchor_spheres_path}")

    centroids = center_of_mass(anchor_data > 0, labeled_anchors, range(1, num_anchors + 1))
    target_points = [tuple(int(x) for x in np.rint(c).astype(np.int64).tolist()) for c in centroids]

    print("=" * 100)
    print("[TARGET POINTS FROM DUODENUM ANCHOR SPHERES]")
    print(f"[N TARGETS] {len(target_points)}")
    for i, p in enumerate(target_points, start=1):
        print(f"  Target {i}: {p}, CT HU={float(ct_data[p]):.1f}")
    print("=" * 100)

    if len(target_points) != 3:
        print(
            f"[WARNING] Expected 3 target anchor spheres, but found {len(target_points)}. "
            "The script will still trace one path per detected target."
        )

    return target_points


# ============================================================
# 6. Dijkstra Path Finder
# ============================================================
def voxel_step_cost(hu_val: float) -> float:
    """
    HU-based cost function inherited from the original script.
    """
    step_cost = 1.0

    if hu_val < 40:
        hu_penalty = (40 - hu_val) ** 2 + 100
    else:
        hu_penalty = max(0, 100 - hu_val)

    return float(step_cost + hu_penalty)


def dijkstra_pathfinder(
    ct_data: np.ndarray,
    start: Tuple[int, int, int],
    end: Tuple[int, int, int],
) -> Tuple[Optional[List[Tuple[int, int, int]]], float]:
    """
    Dijkstra path search with constraints:
      1. HU cost function
      2. Y-axis spatial limit: y <= Y_LIMIT_MAX
      3. optional avoidance of invalid voxels HU == -1024

    Renal exclusion is intentionally removed for run.py integration.
    """
    rows, cols, slices = ct_data.shape

    if not is_inside_shape(start, ct_data.shape):
        raise ValueError(f"Start point out of bounds: {start}")
    if not is_inside_shape(end, ct_data.shape):
        raise ValueError(f"End point out of bounds: {end}")

    queue = [(0.0, start)]
    distances = {start: 0.0}
    predecessor = {start: None}

    neighbors = [(1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 1), (0, 0, -1)]

    while queue:
        curr_cost, curr_pos = heapq.heappop(queue)

        if curr_pos == end:
            path = []
            p = curr_pos
            while p is not None:
                path.append(p)
                p = predecessor[p]
            path = path[::-1]
            return path, float(curr_cost)

        if curr_cost > distances.get(curr_pos, float("inf")):
            continue

        for dx, dy, dz in neighbors:
            next_pos = (curr_pos[0] + dx, curr_pos[1] + dy, curr_pos[2] + dz)

            if not (0 <= next_pos[0] < rows and 0 <= next_pos[1] < cols and 0 <= next_pos[2] < slices):
                continue

            # Constraint 1: Y-axis spatial limit.
            if next_pos[1] > Y_LIMIT_MAX:
                continue

            hu_val = float(ct_data[next_pos])

            # Constraint 2: avoid outside-ROI voxels when requested.
            if AVOID_INVALID_HU and hu_val == INVALID_HU_VALUE:
                continue

            new_cost = curr_cost + voxel_step_cost(hu_val)

            if new_cost < distances.get(next_pos, float("inf")):
                distances[next_pos] = new_cost
                predecessor[next_pos] = curr_pos
                heapq.heappush(queue, (new_cost, next_pos))

    return None, float("inf")


# ============================================================
# 7. Pairing Optimization
# ============================================================
def compute_all_start_target_paths(
    ct_data: np.ndarray,
    start_points: List[Tuple[int, int, int]],
    target_points: List[Tuple[int, int, int]],
) -> Dict[Tuple[int, int], Dict]:
    """
    Compute Dijkstra path for every start-target pair.
    Key = (start_index, target_index), both 0-based.
    """
    results: Dict[Tuple[int, int], Dict] = {}

    print("=" * 100)
    print("[COMPUTE ALL START-TARGET PATHS]")
    print(f"[N STARTS ] {len(start_points)}")
    print(f"[N TARGETS] {len(target_points)}")
    print("=" * 100)

    for si, start in enumerate(start_points):
        for ti, target in enumerate(target_points):
            print("-" * 100)
            print(f"[PATH CANDIDATE] start {si + 1}/{len(start_points)} {start} -> target {ti + 1}/{len(target_points)} {target}")

            path, cost = dijkstra_pathfinder(ct_data, start, target)

            if path is None:
                print("  [FAILED] No feasible path found.")
                results[(si, ti)] = {
                    "path": None,
                    "cost": float("inf"),
                    "num_voxels": 0,
                }
            else:
                print(f"  [OK] cost={cost:.3f}, path voxels={len(path):,}")
                results[(si, ti)] = {
                    "path": path,
                    "cost": float(cost),
                    "num_voxels": int(len(path)),
                }

    return results


def choose_best_assignment(
    path_results: Dict[Tuple[int, int], Dict],
    num_starts: int,
    num_targets: int,
) -> Tuple[List[int], float]:
    """
    Choose one start for each target to minimize total path cost.

    If two starting points are found and three targets exist, this checks all 2^3
    start-target pairing choices and selects the shortest total cost.
    """
    best_assignment = None
    best_total_cost = float("inf")

    for assignment in itertools.product(range(num_starts), repeat=num_targets):
        total_cost = 0.0
        feasible = True

        for target_idx, start_idx in enumerate(assignment):
            cost = path_results[(start_idx, target_idx)]["cost"]
            if not np.isfinite(cost):
                feasible = False
                break
            total_cost += cost

        if feasible and total_cost < best_total_cost:
            best_total_cost = float(total_cost)
            best_assignment = list(assignment)

    if best_assignment is None:
        raise RuntimeError("No feasible start-target assignment was found.")

    print("=" * 100)
    print("[BEST START-TARGET ASSIGNMENT]")
    print(f"[TOTAL COST] {best_total_cost:.3f}")
    for target_idx, start_idx in enumerate(best_assignment):
        print(f"  Target {target_idx + 1} uses Start {start_idx + 1} | cost={path_results[(start_idx, target_idx)]['cost']:.3f}")
    print("=" * 100)

    return best_assignment, best_total_cost


# ============================================================
# 8. Output Rendering
# ============================================================
def render_paths_to_labelmap(
    ct_data: np.ndarray,
    selected_paths: List[List[Tuple[int, int, int]]],
) -> np.ndarray:
    vessel_web_mask = np.zeros(ct_data.shape, dtype=np.uint16)
    struct = np.ones((3, 3, 3), dtype=bool)

    for i, path in enumerate(selected_paths):
        segment_id = i + 1
        temp_path_mask = np.zeros(ct_data.shape, dtype=bool)

        for p in path:
            temp_path_mask[p] = True

        dilated_path = binary_dilation(
            temp_path_mask,
            structure=struct,
            iterations=PATH_DILATION_ITERATIONS,
        )

        # Preserve earlier labels if overlap occurs.
        write_mask = dilated_path & (vessel_web_mask == 0)
        vessel_web_mask[write_mask] = segment_id

    return vessel_web_mask


def write_summary(
    summary_path: Path,
    case_id: str,
    start_points: List[Tuple[int, int, int]],
    target_points: List[Tuple[int, int, int]],
    best_assignment: List[int],
    best_total_cost: float,
    path_results: Dict[Tuple[int, int], Dict],
) -> None:
    with open(summary_path, "w", encoding="utf-8") as f:
        f.write(f"case_id\t{case_id}\n")
        f.write(f"start_source\t{START_VOLUME_NAME}\n")
        f.write(f"y_limit_max\t{Y_LIMIT_MAX}\n")
        f.write(f"avoid_invalid_hu\t{AVOID_INVALID_HU}\n")
        f.write(f"invalid_hu_value\t{INVALID_HU_VALUE}\n")
        f.write(f"best_total_cost\t{best_total_cost:.6f}\n")
        f.write("\n")

        f.write("START_POINTS\n")
        f.write("start_index\tx\ty\tz\n")
        for i, p in enumerate(start_points, start=1):
            f.write(f"{i}\t{p[0]}\t{p[1]}\t{p[2]}\n")
        f.write("\n")

        f.write("TARGET_POINTS\n")
        f.write("target_index\tx\ty\tz\n")
        for i, p in enumerate(target_points, start=1):
            f.write(f"{i}\t{p[0]}\t{p[1]}\t{p[2]}\n")
        f.write("\n")

        f.write("SELECTED_PATHS\n")
        f.write("path_label\ttarget_index\tstart_index\tstart_x\tstart_y\tstart_z\ttarget_x\ttarget_y\ttarget_z\tcost\tpath_voxels\n")
        for target_idx, start_idx in enumerate(best_assignment):
            start = start_points[start_idx]
            target = target_points[target_idx]
            result = path_results[(start_idx, target_idx)]
            f.write(
                f"{target_idx + 1}\t{target_idx + 1}\t{start_idx + 1}\t"
                f"{start[0]}\t{start[1]}\t{start[2]}\t"
                f"{target[0]}\t{target[1]}\t{target[2]}\t"
                f"{result['cost']:.6f}\t{result['num_voxels']}\n"
            )


# ============================================================
# 9. Main Pipeline Function
# ============================================================
def run_gda_pathfinding(case_id: str, ct_path: Path) -> Tuple[Path, Path]:
    # Use the original CT selected in run.py, not ROI_CT.
    anchor_path = build_anchor_spheres_path(case_id)
    anchor_txt_path = build_anchor_points_txt_path(case_id)
    output_path = build_output_path(case_id)
    summary_path = build_summary_path(case_id)

    print("=" * 100)
    print("[GDA PATHFINDING - RUN.PY VERSION]")
    print(f"[CASE ID] {case_id}")
    print(f"[CT     ] {ct_path}")
    print(f"[ANCHOR] {anchor_path}")
    print(f"[START TXT] {anchor_txt_path}")
    print(f"[OUTPUT] {output_path}")
    print("=" * 100)

    ensure_dir(output_path.parent)

    if SKIP_IF_FINAL_EXISTS and output_path.exists() and summary_path.exists():
        print(f"[SKIP] GDA output already exists: {output_path}")
        print(f"[SKIP] GDA summary already exists: {summary_path}")
        return output_path, summary_path

    ct_img, ct_data = load_nifti(ct_path)
    print(f"[INFO] CT shape: {ct_data.shape}")
    print(f"[INFO] CT HU range: min={ct_data.min():.1f}, max={ct_data.max():.1f}")

    start_points = get_start_points_from_search3231(anchor_txt_path, ct_data)
    target_points = get_target_points_from_anchor_spheres(anchor_path, ct_data)

    path_results = compute_all_start_target_paths(
        ct_data=ct_data,
        start_points=start_points,
        target_points=target_points,
    )

    best_assignment, best_total_cost = choose_best_assignment(
        path_results=path_results,
        num_starts=len(start_points),
        num_targets=len(target_points),
    )

    selected_paths = []
    for target_idx, start_idx in enumerate(best_assignment):
        selected_path = path_results[(start_idx, target_idx)]["path"]
        if selected_path is None:
            raise RuntimeError("Internal error: selected assignment contains a failed path.")
        selected_paths.append(selected_path)

    vessel_web_mask = render_paths_to_labelmap(ct_data, selected_paths)

    output_header = ct_img.header.copy()
    output_header.set_data_dtype(np.uint16)

    output_img = nib.Nifti1Image(
        vessel_web_mask.astype(np.uint16),
        affine=ct_img.affine,
        header=output_header,
    )
    nib.save(output_img, str(output_path))

    if not output_path.exists():
        raise RuntimeError(f"GDA output was not created: {output_path}")

    write_summary(
        summary_path=summary_path,
        case_id=case_id,
        start_points=start_points,
        target_points=target_points,
        best_assignment=best_assignment,
        best_total_cost=best_total_cost,
        path_results=path_results,
    )

    print("=" * 100)
    print("[DONE] GDA pathfinding completed.")
    print(f"[OUTPUT MASK] {output_path}")
    print(f"[SUMMARY    ] {summary_path}")
    print("=" * 100)

    return output_path, summary_path


# ============================================================
# 10. Command-Line Interface for run.py
# ============================================================
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run GDA pathfinding from search3231 starting points to duodenum anchor spheres using the original CT selected by run.py."
    )

    parser.add_argument(
        "--ct_path",
        required=True,
        help="Original CT path passed by run.py. This CT is used for GDA pathfinding.",
    )

    parser.add_argument(
        "--output_dir",
        required=True,
        help="Output directory passed by run.py. Accepted for compatibility.",
    )

    parser.add_argument(
        "--case_id",
        required=False,
        default=None,
        help="Case ID passed by run.py. If omitted, inferred from CT filename.",
    )

    return parser.parse_args()


# ============================================================
# 11. Main Entry Point
# ============================================================
def main() -> None:
    args = parse_args()
    ct_path = Path(args.ct_path).resolve()

    case_id = args.case_id.strip() if args.case_id else strip_nii_extension(ct_path.name)
    if not case_id:
        raise ValueError("case_id is empty.")

    run_gda_pathfinding(case_id=case_id, ct_path=ct_path)


if __name__ == "__main__":
    main()
