import argparse
import heapq
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import nibabel as nib
import numpy as np
from scipy.ndimage import binary_dilation

try:
    from nilearn.image import resample_to_img
    HAS_NILEARN = True
except Exception:
    HAS_NILEARN = False


# ============================================================
# 1. Global Settings
# ============================================================
BASE_DIR = Path(r"C:\Users\User\Desktop\AbdVesselGen")
ROI_CT_ROOT = BASE_DIR / "ROI_CT"
ANCHOR_POINTS_ROOT = BASE_DIR / "AnchorPoints"
RESULTS_INTERMEDIATE_ROOT = BASE_DIR / "Results" / "Intermediate"

INVALID_HU_VALUE = -1024

# Start-point file generated by RenalStartExtract.py.
# This file contains labels 101 / 201 / 301 / 401.
START_POINTS_SUFFIX = "renal_start_points_from_restrict_masks"

# Renal hilum file generated by FindRenalHilum.py.
# This file contains label 2 and label 3.
RENAL_HILUM_SUFFIX = "renal_hilum_seg2_seg3_centroid_spheres_diameter6"

OUTPUT_FILENAME = "renal_artery_vein_paths.nii.gz"
SUMMARY_FILENAME = "renal_artery_vein_paths_summary.txt"

# Path rendering width.
PATH_DILATION_ITERATIONS = 1

# Try to keep paths apart. If strict spacing fails, the script retries without spacing
# and records that in the summary instead of stopping the whole pipeline.
MIN_PATH_DISTANCE_VOXELS = 2
ROOT_RELAX_DISTANCE = 5.0
END_RELAX_DISTANCE = 5.0

USE_26_NEIGHBOR_PATHFINDING = True
DIJKSTRA_BBOX_MARGINS = [40, 80, 120, None]

# Endpoint fallback if renal hilum centroid lands on HU == -1024.
ENDPOINT_SEARCH_MAX_RADIUS = 60
ENDPOINT_DISTANCE_TOLERANCE = 1.5

# Start selection from extracted start-point spheres.
START_MIN_HU_PREFERRED = 20

SKIP_IF_FINAL_EXISTS = True


# ============================================================
# 2. Task Definition
# ============================================================
@dataclass
class RenalPathTask:
    name: str
    start_label: int
    target_hilum_label: int
    direction: str
    output_label: int


# User-defined routes:
#   Segment 301 -> right
#   Segment 101 -> left
#   Segment 201 -> right
#   Segment 401 -> left
# Renal hilum:
#   Segment 2 = left renal hilum
#   Segment 3 = right renal hilum
RENAL_PATH_TASKS = [
    RenalPathTask(
        name="renal_vein_Lt_to_right_hilum",
        start_label=301,
        target_hilum_label=3,
        direction="right",
        output_label=1,
    ),
    RenalPathTask(
        name="renal_artery_Lt_to_left_hilum",
        start_label=101,
        target_hilum_label=2,
        direction="left",
        output_label=2,
    ),
    RenalPathTask(
        name="renal_artery_Rt_to_right_hilum",
        start_label=201,
        target_hilum_label=3,
        direction="right",
        output_label=3,
    ),
    RenalPathTask(
        name="renal_vein_Rt_to_left_hilum",
        start_label=401,
        target_hilum_label=2,
        direction="left",
        output_label=4,
    ),
]


# ============================================================
# 3. Path Builders
# ============================================================
def build_roi_ct_path(case_id: str) -> Path:
    return ROI_CT_ROOT / f"{case_id}_ROI_CT.nii.gz"


def build_start_points_path(case_id: str) -> Path:
    return ANCHOR_POINTS_ROOT / f"{case_id}_{START_POINTS_SUFFIX}.nii.gz"


def build_renal_hilum_path(case_id: str) -> Path:
    return ANCHOR_POINTS_ROOT / f"{case_id}_{RENAL_HILUM_SUFFIX}.nii.gz"


def build_output_path(case_id: str) -> Path:
    return RESULTS_INTERMEDIATE_ROOT / f"{case_id}_{OUTPUT_FILENAME}"


def build_summary_path(case_id: str) -> Path:
    return RESULTS_INTERMEDIATE_ROOT / f"{case_id}_{SUMMARY_FILENAME}"


# ============================================================
# 4. Utility Functions
# ============================================================
def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def strip_nii_extension(filename: str) -> str:
    lower = filename.lower()
    if lower.endswith(".nii.gz"):
        return filename[:-7]
    if lower.endswith(".nii"):
        return filename[:-4]
    return Path(filename).stem


def load_nifti(path: Path):
    if not path.exists():
        raise FileNotFoundError(f"File not found:\n{path}")
    img = nib.load(str(path))
    data = img.get_fdata()
    return img, data


def is_inside_shape(point: Tuple[int, int, int], shape: Tuple[int, int, int]) -> bool:
    x, y, z = point
    sx, sy, sz = shape
    return 0 <= x < sx and 0 <= y < sy and 0 <= z < sz


def align_mask_to_ct_if_needed(mask_img, mask_data: np.ndarray, ct_img, name: str):
    ct_shape = ct_img.shape[:3]

    if mask_data.shape == ct_shape and np.allclose(mask_img.affine, ct_img.affine, atol=1e-4):
        print(f"[INFO] {name} already matches ROI_CT geometry.")
        return mask_img, mask_data

    print(f"[WARNING] {name} geometry does not match ROI_CT geometry.")

    if not HAS_NILEARN:
        raise RuntimeError(
            f"{name} geometry differs from ROI_CT, but nilearn is not available for resampling.\n"
            "Please install nilearn or ensure the mask is already aligned."
        )

    print(f"[INFO] Resampling {name} to ROI_CT using nearest-neighbor interpolation...")
    aligned_img = resample_to_img(mask_img, ct_img, interpolation="nearest")
    aligned_data = aligned_img.get_fdata()
    return aligned_img, aligned_data


def get_neighbor_offsets(use_26_neighbor: bool = USE_26_NEIGHBOR_PATHFINDING) -> List[Tuple[int, int, int, float]]:
    offsets: List[Tuple[int, int, int, float]] = []

    if use_26_neighbor:
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                for dz in (-1, 0, 1):
                    if dx == 0 and dy == 0 and dz == 0:
                        continue
                    offsets.append((dx, dy, dz, float(np.sqrt(dx * dx + dy * dy + dz * dz))))
    else:
        for dx, dy, dz in [
            (1, 0, 0), (-1, 0, 0),
            (0, 1, 0), (0, -1, 0),
            (0, 0, 1), (0, 0, -1),
        ]:
            offsets.append((dx, dy, dz, 1.0))

    return offsets


# ============================================================
# 5. Start and Endpoint Selection
# ============================================================
def select_start_point_from_label(
    ct_data: np.ndarray,
    start_data: np.ndarray,
    start_label: int,
    direction: str,
) -> Tuple[int, int, int]:
    start_int = np.rint(start_data).astype(np.int32)
    coords = np.argwhere(start_int == int(start_label))

    if len(coords) == 0:
        available = [int(x) for x in np.unique(start_int) if x > 0]
        raise RuntimeError(
            f"Start label {start_label} was not found in start-point mask.\n"
            f"Available positive labels: {available}\n"
            "Expected labels are 101, 201, 301, and 401 from RenalStartExtract.py."
        )

    hu_values = ct_data[coords[:, 0], coords[:, 1], coords[:, 2]]
    valid_mask = hu_values != INVALID_HU_VALUE

    if not np.any(valid_mask):
        raise RuntimeError(f"Start label {start_label} has no voxel with HU != {INVALID_HU_VALUE}.")

    valid_coords = coords[valid_mask]
    valid_hu = hu_values[valid_mask]

    preferred_mask = valid_hu > START_MIN_HU_PREFERRED
    if np.any(preferred_mask):
        candidate_coords = valid_coords[preferred_mask]
        candidate_hu = valid_hu[preferred_mask]
    else:
        candidate_coords = valid_coords
        candidate_hu = valid_hu

    centroid = candidate_coords.astype(np.float64).mean(axis=0)
    dists = np.linalg.norm(candidate_coords.astype(np.float64) - centroid[None, :], axis=1)

    # Here index-0 is treated as the left-right axis, consistent with your prior scripts.
    x_values = candidate_coords[:, 0]
    if direction.lower() == "right":
        extreme_x = int(np.max(x_values))
    elif direction.lower() == "left":
        extreme_x = int(np.min(x_values))
    else:
        raise ValueError(f"Unsupported direction: {direction}")

    extreme_mask = x_values == extreme_x
    extreme_coords = candidate_coords[extreme_mask]
    extreme_hu = candidate_hu[extreme_mask]
    extreme_dists = dists[extreme_mask]

    # Prefer higher HU, then closer to local centroid.
    order = np.lexsort((extreme_dists, -extreme_hu))
    best = extreme_coords[int(order[0])]
    point = tuple(int(v) for v in best.tolist())

    print(
        f"[START] label={start_label}, direction={direction}, point={point}, "
        f"HU={float(ct_data[point]):.1f}, candidates={len(candidate_coords):,}"
    )
    return point


def find_valid_endpoint_for_hilum_label(
    ct_data: np.ndarray,
    hilum_data: np.ndarray,
    hilum_label: int,
    max_radius: int = ENDPOINT_SEARCH_MAX_RADIUS,
    distance_tolerance: float = ENDPOINT_DISTANCE_TOLERANCE,
) -> Tuple[int, int, int]:
    hilum_int = np.rint(hilum_data).astype(np.int32)
    coords = np.argwhere(hilum_int == int(hilum_label))

    if len(coords) == 0:
        available = [int(x) for x in np.unique(hilum_int) if x > 0]
        raise RuntimeError(
            f"Renal hilum label {hilum_label} was not found.\n"
            f"Available positive labels: {available}\n"
            "Expected label 2 for left renal hilum and label 3 for right renal hilum."
        )

    centroid = coords.astype(np.float64).mean(axis=0)
    rounded = tuple(int(v) for v in np.rint(centroid).astype(np.int64).tolist())

    if is_inside_shape(rounded, ct_data.shape) and float(ct_data[rounded]) != INVALID_HU_VALUE:
        print(
            f"[ENDPOINT] hilum_label={hilum_label}, using rounded centroid={rounded}, "
            f"HU={float(ct_data[rounded]):.1f}"
        )
        return rounded

    print(
        f"[WARNING] Hilum label {hilum_label} rounded centroid {rounded} is invalid. "
        "Searching nearest valid endpoint."
    )

    shape = np.array(ct_data.shape, dtype=np.int64)
    sphere_min = coords.min(axis=0)
    sphere_max = coords.max(axis=0)

    from scipy.spatial import KDTree
    tree = KDTree(coords)

    for radius in range(0, max_radius + 1):
        min_corner = np.maximum(0, sphere_min - radius)
        max_corner = np.minimum(shape - 1, sphere_max + radius)
        sx0, sy0, sz0 = [int(x) for x in min_corner]
        sx1, sy1, sz1 = [int(x) for x in max_corner]

        sub_ct = ct_data[sx0:sx1 + 1, sy0:sy1 + 1, sz0:sz1 + 1]
        valid = sub_ct != INVALID_HU_VALUE

        if not np.any(valid):
            continue

        local_coords = np.argwhere(valid)
        global_coords = local_coords + np.array([sx0, sy0, sz0], dtype=np.int64)
        hu_values = ct_data[global_coords[:, 0], global_coords[:, 1], global_coords[:, 2]]

        distances, _ = tree.query(global_coords)
        min_distance = float(np.min(distances))
        close_mask = distances <= (min_distance + distance_tolerance)

        close_coords = global_coords[close_mask]
        close_hu = hu_values[close_mask]
        close_dist = distances[close_mask]

        # Among similarly close points, prefer higher HU.
        order = np.lexsort((close_dist, -close_hu))
        best_idx = int(order[0])
        best = close_coords[best_idx]
        endpoint = tuple(int(v) for v in best.tolist())

        print(
            f"[ENDPOINT] hilum_label={hilum_label}, fallback={endpoint}, "
            f"HU={float(ct_data[endpoint]):.1f}, distance={float(close_dist[best_idx]):.3f}, radius={radius}"
        )
        return endpoint

    raise RuntimeError(f"No valid endpoint found near renal hilum label {hilum_label} within radius {max_radius}.")


# ============================================================
# 6. Dijkstra Pathfinding
# ============================================================
def voxel_step_cost(hu_val: float) -> float:
    # Adapted from your RL_pathfind style: avoid low HU, prefer enhancing structures.
    step_cost = 1.0
    if hu_val < 40:
        hu_penalty = (40 - hu_val) ** 2 + 100
    else:
        hu_penalty = max(0, 100 - hu_val)
    return float(step_cost + hu_penalty)


def make_bbox_bounds(
    shape: Tuple[int, int, int],
    start: Tuple[int, int, int],
    end: Tuple[int, int, int],
    margin: Optional[int],
) -> Tuple[np.ndarray, np.ndarray]:
    shape_arr = np.array(shape, dtype=np.int64)
    if margin is None:
        return np.array([0, 0, 0], dtype=np.int64), shape_arr - 1

    start_arr = np.array(start, dtype=np.int64)
    end_arr = np.array(end, dtype=np.int64)
    lower = np.maximum(0, np.minimum(start_arr, end_arr) - int(margin))
    upper = np.minimum(shape_arr - 1, np.maximum(start_arr, end_arr) + int(margin))
    return lower, upper


def dijkstra_pathfinder_once(
    ct_data: np.ndarray,
    start: Tuple[int, int, int],
    end: Tuple[int, int, int],
    exclusion_mask: Optional[np.ndarray] = None,
    bbox_margin: Optional[int] = None,
) -> Tuple[Optional[List[Tuple[int, int, int]]], float, int]:
    rows, cols, slices = ct_data.shape

    if not is_inside_shape(start, ct_data.shape):
        raise ValueError(f"Start point out of bounds: {start}")
    if not is_inside_shape(end, ct_data.shape):
        raise ValueError(f"End point out of bounds: {end}")

    if float(ct_data[start]) == INVALID_HU_VALUE:
        print(f"[WARNING] Start point has invalid HU: {start}")
        return None, float("inf"), 0
    if float(ct_data[end]) == INVALID_HU_VALUE:
        print(f"[WARNING] End point has invalid HU: {end}")
        return None, float("inf"), 0

    lower, upper = make_bbox_bounds(ct_data.shape, start, end, bbox_margin)

    queue = [(0.0, start)]
    distances = {start: 0.0}
    predecessor = {start: None}
    neighbors = get_neighbor_offsets(USE_26_NEIGHBOR_PATHFINDING)
    visited = set()
    expanded_nodes = 0

    start_arr = np.array(start, dtype=np.float64)
    end_arr = np.array(end, dtype=np.float64)

    while queue:
        curr_cost, curr_pos = heapq.heappop(queue)

        if curr_pos in visited:
            continue
        visited.add(curr_pos)
        expanded_nodes += 1

        if curr_pos == end:
            path = []
            p = curr_pos
            while p is not None:
                path.append(p)
                p = predecessor[p]
            path = path[::-1]
            return path, float(curr_cost), expanded_nodes

        if curr_cost > distances.get(curr_pos, float("inf")):
            continue

        for dx, dy, dz, movement_length in neighbors:
            next_pos = (curr_pos[0] + dx, curr_pos[1] + dy, curr_pos[2] + dz)

            if not (0 <= next_pos[0] < rows and 0 <= next_pos[1] < cols and 0 <= next_pos[2] < slices):
                continue

            next_arr_i = np.array(next_pos, dtype=np.int64)
            if np.any(next_arr_i < lower) or np.any(next_arr_i > upper):
                continue

            hu_val = float(ct_data[next_pos])
            if hu_val == INVALID_HU_VALUE:
                continue

            if exclusion_mask is not None and exclusion_mask[next_pos]:
                next_arr = np.array(next_pos, dtype=np.float64)
                dist_to_start = float(np.linalg.norm(next_arr - start_arr))
                dist_to_end = float(np.linalg.norm(next_arr - end_arr))

                # Allow sharing near the root and hilum; exclude elsewhere.
                if dist_to_start > ROOT_RELAX_DISTANCE and dist_to_end > END_RELAX_DISTANCE:
                    continue

            new_cost = curr_cost + movement_length * voxel_step_cost(hu_val)

            if new_cost < distances.get(next_pos, float("inf")):
                distances[next_pos] = new_cost
                predecessor[next_pos] = curr_pos
                heapq.heappush(queue, (new_cost, next_pos))

    return None, float("inf"), expanded_nodes


def dijkstra_pathfinder(
    ct_data: np.ndarray,
    start: Tuple[int, int, int],
    end: Tuple[int, int, int],
    exclusion_mask: Optional[np.ndarray] = None,
) -> Tuple[Optional[List[Tuple[int, int, int]]], float]:
    print(f"  [Dijkstra] Connectivity: {'26-neighbor' if USE_26_NEIGHBOR_PATHFINDING else '6-neighbor'}")

    for margin in DIJKSTRA_BBOX_MARGINS:
        margin_text = "full-volume" if margin is None else f"bbox margin {margin}"
        print(f"  [Dijkstra] Trying {margin_text}...")
        path, cost, expanded = dijkstra_pathfinder_once(
            ct_data=ct_data,
            start=start,
            end=end,
            exclusion_mask=exclusion_mask,
            bbox_margin=margin,
        )

        if path is not None:
            print(f"  [Dijkstra] Success with {margin_text}. Expanded nodes: {expanded:,}")
            return path, cost

        print(f"  [Dijkstra] Failed with {margin_text}. Expanded nodes: {expanded:,}")

    return None, float("inf")


# ============================================================
# 7. Path Spacing and Rendering
# ============================================================
def path_to_mask(shape: Tuple[int, int, int], path: List[Tuple[int, int, int]]) -> np.ndarray:
    mask = np.zeros(shape, dtype=bool)
    for p in path:
        mask[p] = True
    return mask


def build_spacing_exclusion_from_paths(
    shape: Tuple[int, int, int],
    paths: List[List[Tuple[int, int, int]]],
    spacing_voxels: int = MIN_PATH_DISTANCE_VOXELS,
) -> np.ndarray:
    if not paths:
        return np.zeros(shape, dtype=bool)

    base = np.zeros(shape, dtype=bool)
    for path in paths:
        for p in path:
            base[p] = True

    structure = np.ones((3, 3, 3), dtype=bool)
    return binary_dilation(base, structure=structure, iterations=int(spacing_voxels))


def render_paths_to_labelmap(
    shape: Tuple[int, int, int],
    labeled_paths: List[Tuple[int, List[Tuple[int, int, int]]]],
) -> np.ndarray:
    output = np.zeros(shape, dtype=np.uint16)
    structure = np.ones((3, 3, 3), dtype=bool)

    for label_value, path in labeled_paths:
        path_mask = path_to_mask(shape, path)
        dilated = binary_dilation(path_mask, structure=structure, iterations=PATH_DILATION_ITERATIONS)
        write_mask = dilated & (output == 0)
        output[write_mask] = int(label_value)

    return output


# ============================================================
# 8. Main Pipeline
# ============================================================
def run_renal_pathfinder(case_id: str) -> Tuple[Path, Path]:
    ct_path = build_roi_ct_path(case_id)
    start_points_path = build_start_points_path(case_id)
    renal_hilum_path = build_renal_hilum_path(case_id)
    output_path = build_output_path(case_id)
    summary_path = build_summary_path(case_id)

    print("=" * 100)
    print("[RENAL ARTERY / VEIN PATHFINDER - RUN.PY VERSION]")
    print(f"[CASE ID      ] {case_id}")
    print(f"[ROI CT       ] {ct_path}")
    print(f"[START POINTS ] {start_points_path}")
    print(f"[RENAL HILUM  ] {renal_hilum_path}")
    print(f"[OUTPUT       ] {output_path}")
    print("=" * 100)

    ensure_dir(output_path.parent)

    if SKIP_IF_FINAL_EXISTS and output_path.exists() and summary_path.exists():
        print(f"[SKIP] Output already exists: {output_path}")
        print(f"[SKIP] Summary already exists: {summary_path}")
        return output_path, summary_path

    ct_img, ct_data = load_nifti(ct_path)
    start_img_raw, start_data_raw = load_nifti(start_points_path)
    hilum_img_raw, hilum_data_raw = load_nifti(renal_hilum_path)

    _, start_data = align_mask_to_ct_if_needed(start_img_raw, start_data_raw, ct_img, "renal start points")
    _, hilum_data = align_mask_to_ct_if_needed(hilum_img_raw, hilum_data_raw, ct_img, "renal hilum mask")

    print(f"[INFO] ROI_CT shape: {ct_data.shape}")
    print(f"[INFO] ROI_CT HU range: min={ct_data.min():.1f}, max={ct_data.max():.1f}")
    print(f"[INFO] Start labels present: {[int(x) for x in np.unique(np.rint(start_data).astype(np.int32)) if x > 0]}")
    print(f"[INFO] Hilum labels present: {[int(x) for x in np.unique(np.rint(hilum_data).astype(np.int32)) if x > 0]}")

    traced_paths: List[List[Tuple[int, int, int]]] = []
    labeled_paths: List[Tuple[int, List[Tuple[int, int, int]]]] = []
    records: List[Dict] = []

    for task in RENAL_PATH_TASKS:
        print("\n" + "=" * 100)
        print(f"[PATH TASK] {task.name}")
        print(
            f"[INFO] start_label={task.start_label}, direction={task.direction}, "
            f"target_hilum_label={task.target_hilum_label}, output_label={task.output_label}"
        )
        print("=" * 100)

        start_point = select_start_point_from_label(
            ct_data=ct_data,
            start_data=start_data,
            start_label=task.start_label,
            direction=task.direction,
        )

        endpoint = find_valid_endpoint_for_hilum_label(
            ct_data=ct_data,
            hilum_data=hilum_data,
            hilum_label=task.target_hilum_label,
            max_radius=ENDPOINT_SEARCH_MAX_RADIUS,
            distance_tolerance=ENDPOINT_DISTANCE_TOLERANCE,
        )

        exclusion_mask = build_spacing_exclusion_from_paths(
            shape=ct_data.shape,
            paths=traced_paths,
            spacing_voxels=MIN_PATH_DISTANCE_VOXELS,
        )

        path, cost = dijkstra_pathfinder(
            ct_data=ct_data,
            start=start_point,
            end=endpoint,
            exclusion_mask=exclusion_mask,
        )

        spacing_status = "strict_spacing_ok"
        if path is None:
            print(f"[WARNING] Strict spacing failed for {task.name}. Retrying without spacing exclusion.")
            path, cost = dijkstra_pathfinder(
                ct_data=ct_data,
                start=start_point,
                end=endpoint,
                exclusion_mask=None,
            )
            spacing_status = "retried_without_spacing"

        if path is None:
            raise RuntimeError(f"Path search failed for task: {task.name}")

        traced_paths.append(path)
        labeled_paths.append((task.output_label, path))

        path_hu = np.array([ct_data[p] for p in path], dtype=np.float64)
        print(
            f"[OK] {task.name}: path_voxels={len(path):,}, cost={cost:.3f}, "
            f"mean_HU={float(path_hu.mean()):.2f}, min_HU={float(path_hu.min()):.2f}, "
            f"max_HU={float(path_hu.max()):.2f}, spacing_status={spacing_status}"
        )

        records.append({
            "task_name": task.name,
            "start_label": task.start_label,
            "direction": task.direction,
            "target_hilum_label": task.target_hilum_label,
            "output_label": task.output_label,
            "start_x": start_point[0],
            "start_y": start_point[1],
            "start_z": start_point[2],
            "start_hu": float(ct_data[start_point]),
            "end_x": endpoint[0],
            "end_y": endpoint[1],
            "end_z": endpoint[2],
            "end_hu": float(ct_data[endpoint]),
            "cost": float(cost),
            "path_voxels": int(len(path)),
            "mean_hu": float(path_hu.mean()),
            "min_hu": float(path_hu.min()),
            "max_hu": float(path_hu.max()),
            "spacing_status": spacing_status,
        })

    output_labelmap = render_paths_to_labelmap(ct_data.shape, labeled_paths)

    out_header = ct_img.header.copy()
    out_header.set_data_dtype(np.uint16)

    out_img = nib.Nifti1Image(
        output_labelmap.astype(np.uint16),
        affine=ct_img.affine,
        header=out_header,
    )
    nib.save(out_img, str(output_path))

    if not output_path.exists():
        raise RuntimeError(f"Output was not created: {output_path}")

    with open(summary_path, "w", encoding="utf-8") as f:
        f.write(f"case_id\t{case_id}\n")
        f.write(f"roi_ct_path\t{ct_path}\n")
        f.write(f"start_points_path\t{start_points_path}\n")
        f.write(f"renal_hilum_path\t{renal_hilum_path}\n")
        f.write(f"output_path\t{output_path}\n")
        f.write(f"invalid_hu_value\t{INVALID_HU_VALUE}\n")
        f.write(f"min_path_distance_voxels\t{MIN_PATH_DISTANCE_VOXELS}\n")
        f.write(f"root_relax_distance\t{ROOT_RELAX_DISTANCE}\n")
        f.write(f"end_relax_distance\t{END_RELAX_DISTANCE}\n")
        f.write(f"use_26_neighbor_pathfinding\t{USE_26_NEIGHBOR_PATHFINDING}\n")
        f.write(f"dijkstra_bbox_margins\t{DIJKSTRA_BBOX_MARGINS}\n")
        f.write("\n")

        header = [
            "task_name",
            "start_label",
            "direction",
            "target_hilum_label",
            "output_label",
            "start_x",
            "start_y",
            "start_z",
            "start_hu",
            "end_x",
            "end_y",
            "end_z",
            "end_hu",
            "cost",
            "path_voxels",
            "mean_hu",
            "min_hu",
            "max_hu",
            "spacing_status",
        ]
        f.write("\t".join(header) + "\n")
        for r in records:
            row = []
            for key in header:
                value = r[key]
                if isinstance(value, float):
                    row.append(f"{value:.6f}")
                else:
                    row.append(str(value))
            f.write("\t".join(row) + "\n")

    print("\n" + "=" * 100)
    print("[DONE] Renal artery/vein pathfinding completed.")
    print(f"[OUTPUT MASK] {output_path}")
    print(f"[SUMMARY    ] {summary_path}")
    print(f"[INFO] Output labels present: {[int(x) for x in np.unique(output_labelmap) if x > 0]}")
    print("=" * 100)

    return output_path, summary_path


# ============================================================
# 9. Command-Line Interface for run.py
# ============================================================
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Trace renal artery/vein paths from extracted renal start points to renal hilum spheres."
    )

    parser.add_argument(
        "--ct_path",
        required=True,
        help="CT path passed by run.py. Accepted for compatibility; this script uses ROI_CT output.",
    )

    parser.add_argument(
        "--output_dir",
        required=True,
        help="Output directory passed by run.py. Accepted for compatibility; output is written to Results/Intermediate.",
    )

    parser.add_argument(
        "--case_id",
        required=False,
        default=None,
        help="Case ID passed by run.py. If omitted, inferred from CT filename.",
    )

    return parser.parse_args()


# ============================================================
# 10. Main Entry Point
# ============================================================
def main() -> None:
    args = parse_args()
    ct_path = Path(args.ct_path).resolve()

    case_id = args.case_id.strip() if args.case_id else strip_nii_extension(ct_path.name)
    if not case_id:
        raise ValueError("case_id is empty.")

    run_renal_pathfinder(case_id=case_id)


if __name__ == "__main__":
    main()
