import argparse
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import nibabel as nib
from scipy import ndimage


# ============================================================
# 1. Global Settings
# ============================================================
BASE_DIR = Path(r"C:\Users\User\Desktop\AbdVesselGen")
ROI_CT_ROOT = BASE_DIR / "ROI_CT"
ANCHOR_POINTS_ROOT = BASE_DIR / "AnchorPoints"

# Source-specific HU thresholds.
# Anchor points derived from search3231_volume use HU > 80.
# Anchor points derived from search2928_volume use HU > 50.
HU_THRESHOLD_BY_VOLUME = {
    "search3231_volume": 80.0,
    "search2928_volume": 40.0,
}

# 3D 26-connectivity.
CONNECTIVITY_STRUCTURE = np.ones((3, 3, 3), dtype=np.uint8)

# If the final output already exists, skip this step.
SKIP_IF_FINAL_EXISTS = True


# ============================================================
# 2. Path Builders
# ============================================================
def build_roi_ct_path(case_id: str) -> Path:
    return ROI_CT_ROOT / f"{case_id}_ROI_CT.nii.gz"


def build_anchor_points_txt_path(case_id: str) -> Path:
    return ANCHOR_POINTS_ROOT / f"{case_id}_anchor_points_from_search_volumes.txt"


def build_output_mask_path(case_id: str) -> Path:
    """
    Combined labelmap output.

    Each extracted connected component is assigned a unique label:
      Label 1 = first accepted seed component
      Label 2 = second accepted seed component
      ...
    """
    return ANCHOR_POINTS_ROOT / f"{case_id}_ATrace_connected_components.nii.gz"


def build_output_summary_path(case_id: str) -> Path:
    return ANCHOR_POINTS_ROOT / f"{case_id}_ATrace_connected_components_summary.txt"


# ============================================================
# 3. Utility Functions
# ============================================================
def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def strip_nii_extension(filename: str) -> str:
    lower = filename.lower()
    if lower.endswith(".nii.gz"):
        return filename[:-7]
    if lower.endswith(".nii"):
        return filename[:-4]
    return Path(filename).stem


def load_nifti(path: Path):
    if not path.exists():
        raise FileNotFoundError(f"File not found:\n{path}")
    img = nib.load(str(path))
    data = img.get_fdata()
    return img, data


def parse_anchor_points_txt(txt_path: Path) -> List[Dict]:
    """
    Parse the tab-separated anchor point file generated by
    FindAnchorPointsFromSearchVolumes.py.

    Expected data columns include:
      volume_name, component_id, point_x, point_y, point_z, point_hu
    """
    if not txt_path.exists():
        raise FileNotFoundError(f"Anchor points TXT not found:\n{txt_path}")

    records: List[Dict] = []
    header = None

    with open(txt_path, "r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line:
                continue

            parts = line.split("\t")

            # Skip metadata lines such as: case_id\t43_24055
            if len(parts) == 2 and parts[0] in {"case_id", "invalid_hu_value", "max_search_radius"}:
                continue

            if parts[0] == "volume_name":
                header = parts
                continue

            if header is None:
                continue

            if len(parts) != len(header):
                print(f"[WARNING] Skipping malformed row: {line}")
                continue

            row = dict(zip(header, parts))

            try:
                row["component_id"] = int(row["component_id"])
                row["component_voxels"] = int(row["component_voxels"])
                row["centroid_x"] = float(row["centroid_x"])
                row["centroid_y"] = float(row["centroid_y"])
                row["centroid_z"] = float(row["centroid_z"])
                row["point_x"] = int(row["point_x"])
                row["point_y"] = int(row["point_y"])
                row["point_z"] = int(row["point_z"])
                row["point_hu"] = float(row["point_hu"])
                row["distance_to_centroid"] = float(row["distance_to_centroid"])
                row["found_radius"] = int(row["found_radius"])
            except Exception as e:
                print(f"[WARNING] Skipping row because parsing failed: {line}")
                print(f"[WARNING] Error: {e}")
                continue

            records.append(row)

    return records


def is_point_inside_shape(point: Tuple[int, int, int], shape: Tuple[int, int, int]) -> bool:
    x, y, z = point
    sx, sy, sz = shape
    return 0 <= x < sx and 0 <= y < sy and 0 <= z < sz


# ============================================================
# 4. Connected Component Extraction
# ============================================================
def extract_hu_connected_component_from_seed(
    ct_data: np.ndarray,
    start_point: Tuple[int, int, int],
    hu_threshold: float,
) -> Tuple[np.ndarray, Dict]:
    """
    Extract the HU-positive connected component containing start_point.

    Condition:
      ct_data > hu_threshold

    Returns:
      output_mask, info_dict
    """
    shape = ct_data.shape

    if not is_point_inside_shape(start_point, shape):
        raise ValueError(f"Start point {start_point} is out of CT bounds: {shape}")

    start_hu = float(ct_data[start_point])

    hu_mask = ct_data > hu_threshold
    total_hu_positive = int(hu_mask.sum())

    if not hu_mask[start_point]:
        raise RuntimeError(
            f"Start point {start_point} has HU = {start_hu:.1f}, "
            f"which is not > {hu_threshold}."
        )

    labeled_mask, num_components = ndimage.label(
        hu_mask,
        structure=CONNECTIVITY_STRUCTURE,
    )

    seed_component_label = int(labeled_mask[start_point])

    if seed_component_label == 0:
        raise RuntimeError(
            "Unexpected error: seed component label is 0 although seed HU passed threshold."
        )

    output_mask = labeled_mask == seed_component_label
    connected_voxels = int(output_mask.sum())

    info = {
        "start_hu": start_hu,
        "hu_threshold": float(hu_threshold),
        "total_hu_positive": total_hu_positive,
        "num_hu_components": int(num_components),
        "seed_component_label": seed_component_label,
        "connected_voxels": connected_voxels,
    }

    return output_mask.astype(bool), info


# ============================================================
# 5. Main ATrace Pipeline
# ============================================================
def run_atrace_from_anchor_points(case_id: str) -> Tuple[Path, Path]:
    roi_ct_path = build_roi_ct_path(case_id)
    anchor_txt_path = build_anchor_points_txt_path(case_id)
    output_mask_path = build_output_mask_path(case_id)
    output_summary_path = build_output_summary_path(case_id)

    print("=" * 100)
    print("[ATRACE FROM SEARCH-VOLUME ANCHOR POINTS]")
    print(f"[CASE ID ] {case_id}")
    print(f"[ROI CT  ] {roi_ct_path}")
    print(f"[ANCHORS ] {anchor_txt_path}")
    print(f"[OUTPUT  ] {output_mask_path}")
    print("=" * 100)

    ensure_dir(output_mask_path.parent)

    if SKIP_IF_FINAL_EXISTS and output_mask_path.exists() and output_summary_path.exists():
        print(f"[SKIP] ATrace output already exists: {output_mask_path}")
        print(f"[SKIP] ATrace summary already exists: {output_summary_path}")
        return output_mask_path, output_summary_path

    ct_img, ct_data = load_nifti(roi_ct_path)
    print(f"[INFO] ROI CT shape: {ct_data.shape}")
    print(f"[INFO] ROI CT HU range: min={ct_data.min():.1f}, max={ct_data.max():.1f}")

    anchor_records = parse_anchor_points_txt(anchor_txt_path)
    print(f"[INFO] Anchor point records loaded: {len(anchor_records)}")

    if len(anchor_records) == 0:
        raise RuntimeError("No anchor point records found in the TXT file.")

    combined_labelmap = np.zeros(ct_data.shape, dtype=np.uint16)
    summary_records: List[Dict] = []
    output_label = 1

    for idx, record in enumerate(anchor_records, start=1):
        volume_name = record["volume_name"]
        start_point = (
            int(record["point_x"]),
            int(record["point_y"]),
            int(record["point_z"]),
        )

        if volume_name not in HU_THRESHOLD_BY_VOLUME:
            print("-" * 100)
            print(f"[WARNING] Unknown volume_name: {volume_name}")
            print("[WARNING] This anchor point will be skipped because no HU threshold is defined.")
            continue

        hu_threshold = HU_THRESHOLD_BY_VOLUME[volume_name]

        print("\n" + "=" * 100)
        print(f"[ANCHOR {idx}] volume={volume_name}, component_id={record['component_id']}")
        print(f"[ANCHOR {idx}] start_point={start_point}, point_hu={record['point_hu']:.1f}")
        print(f"[ANCHOR {idx}] HU threshold = {hu_threshold}")

        try:
            component_mask, info = extract_hu_connected_component_from_seed(
                ct_data=ct_data,
                start_point=start_point,
                hu_threshold=hu_threshold,
            )
        except Exception as e:
            print(f"[WARNING] Failed to extract component from anchor {idx}: {e}")
            summary_records.append({
                "status": "failed",
                "output_label": 0,
                "volume_name": volume_name,
                "component_id": record["component_id"],
                "start_x": start_point[0],
                "start_y": start_point[1],
                "start_z": start_point[2],
                "point_hu": record["point_hu"],
                "hu_threshold": hu_threshold,
                "connected_voxels": 0,
                "error": str(e),
            })
            continue

        # Preserve earlier labels if overlaps occur. Later components only fill unlabeled voxels.
        write_mask = component_mask & (combined_labelmap == 0)
        newly_written_voxels = int(write_mask.sum())
        overlap_voxels = int(component_mask.sum()) - newly_written_voxels

        combined_labelmap[write_mask] = output_label

        print(f"[INFO] Seed component label in HU mask: {info['seed_component_label']}")
        print(f"[INFO] Extracted connected voxels: {info['connected_voxels']:,}")
        print(f"[INFO] Newly written voxels: {newly_written_voxels:,}")
        print(f"[INFO] Overlap voxels with previous labels: {overlap_voxels:,}")
        print(f"[INFO] Output label assigned: {output_label}")

        summary_records.append({
            "status": "ok",
            "output_label": output_label,
            "volume_name": volume_name,
            "component_id": record["component_id"],
            "start_x": start_point[0],
            "start_y": start_point[1],
            "start_z": start_point[2],
            "point_hu": record["point_hu"],
            "hu_threshold": hu_threshold,
            "start_hu_in_roi_ct": info["start_hu"],
            "total_hu_positive": info["total_hu_positive"],
            "num_hu_components": info["num_hu_components"],
            "seed_component_label": info["seed_component_label"],
            "connected_voxels": info["connected_voxels"],
            "newly_written_voxels": newly_written_voxels,
            "overlap_voxels": overlap_voxels,
            "error": "",
        })

        output_label += 1

    # --------------------------------------------------------
    # Save combined labelmap
    # --------------------------------------------------------
    output_header = ct_img.header.copy()
    output_header.set_data_dtype(np.uint16)

    output_img = nib.Nifti1Image(
        combined_labelmap.astype(np.uint16),
        affine=ct_img.affine,
        header=output_header,
    )
    nib.save(output_img, str(output_mask_path))

    if not output_mask_path.exists():
        raise RuntimeError(f"ATrace output was not created: {output_mask_path}")

    # --------------------------------------------------------
    # Save summary TXT
    # --------------------------------------------------------
    with open(output_summary_path, "w", encoding="utf-8") as f:
        f.write(f"case_id\t{case_id}\n")
        f.write("threshold_rule\tsearch3231_volume: HU > 80; search2928_volume: HU > 50\n")
        f.write("\n")

        header = [
            "status",
            "output_label",
            "volume_name",
            "component_id",
            "start_x",
            "start_y",
            "start_z",
            "point_hu",
            "hu_threshold",
            "start_hu_in_roi_ct",
            "total_hu_positive",
            "num_hu_components",
            "seed_component_label",
            "connected_voxels",
            "newly_written_voxels",
            "overlap_voxels",
            "error",
        ]
        f.write("\t".join(header) + "\n")

        for r in summary_records:
            row = []
            for key in header:
                value = r.get(key, "")
                if isinstance(value, float):
                    row.append(f"{value:.6f}")
                else:
                    row.append(str(value))
            f.write("\t".join(row) + "\n")

    print("\n" + "=" * 100)
    print("[DONE] ATrace completed.")
    print(f"[OUTPUT MASK   ] {output_mask_path}")
    print(f"[OUTPUT SUMMARY] {output_summary_path}")
    print("=" * 100)

    return output_mask_path, output_summary_path


# ============================================================
# 6. Command-Line Interface for run.py
# ============================================================
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run ATrace from anchor points generated from search volumes."
    )

    parser.add_argument(
        "--ct_path",
        required=True,
        help="CT path passed by run.py. Accepted for compatibility; this script uses ROI_CT output.",
    )

    parser.add_argument(
        "--output_dir",
        required=True,
        help="Output directory passed by run.py. Accepted for compatibility.",
    )

    parser.add_argument(
        "--case_id",
        required=False,
        default=None,
        help="Case ID passed by run.py. If omitted, inferred from CT filename.",
    )

    return parser.parse_args()


# ============================================================
# 7. Main Entry Point
# ============================================================
def main() -> None:
    args = parse_args()
    ct_path = Path(args.ct_path).resolve()

    case_id = args.case_id.strip() if args.case_id else strip_nii_extension(ct_path.name)
    if not case_id:
        raise ValueError("case_id is empty.")

    run_atrace_from_anchor_points(case_id=case_id)


if __name__ == "__main__":
    main()
