import argparse
from pathlib import Path
from typing import Dict, List

import numpy as np
import nibabel as nib


# ============================================================
# 1. Global Settings
# ============================================================
BASE_DIR = Path(r"C:\Users\User\Desktop\AbdVesselGen")
SEG_DONE_ROOT = BASE_DIR / "Seg_Done"
ANCHOR_POINTS_ROOT = BASE_DIR / "AnchorPoints"

# Duodenum label in the AllSeg mask.
TARGET_LABELS = [19]

# If output already exists, skip this step.
SKIP_IF_FINAL_EXISTS = True


# ============================================================
# 2. Path Builders
# ============================================================
def build_allseg_path(case_id: str) -> Path:
    """
    Example:
        C:/Users/User/Desktop/AbdVesselGen/Seg_Done/43_24055_All_segmentation/43_24055_All_segmentation.nii
    """
    return SEG_DONE_ROOT / f"{case_id}_All_segmentation" / f"{case_id}_All_segmentation.nii"


def build_anchor_points_txt_path(case_id: str) -> Path:
    """
    Example:
        C:/Users/User/Desktop/AbdVesselGen/AnchorPoints/43_24055_anchor_points_from_search_volumes.txt
    """
    return ANCHOR_POINTS_ROOT / f"{case_id}_anchor_points_from_search_volumes.txt"


def build_output_path(case_id: str) -> Path:
    """
    Example:
        C:/Users/User/Desktop/AbdVesselGen/AnchorPoints/43_24055_bowel_inner_surface_toward_dynamic_center_duodenum.nii.gz
    """
    return ANCHOR_POINTS_ROOT / f"{case_id}_bowel_inner_surface_toward_dynamic_center_duodenum.nii.gz"


# ============================================================
# 3. Utility Functions
# ============================================================
def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def strip_nii_extension(filename: str) -> str:
    lower = filename.lower()
    if lower.endswith(".nii.gz"):
        return filename[:-7]
    if lower.endswith(".nii"):
        return filename[:-4]
    return Path(filename).stem


def load_nifti(path: Path):
    if not path.exists():
        raise FileNotFoundError(f"File not found:\n{path}")
    img = nib.load(str(path))
    data = img.get_fdata()
    return img, data


def parse_anchor_points_txt(txt_path: Path) -> List[Dict]:
    """
    Parse the tab-separated TXT generated by FindAnchorPointsFromSearchVolumes.py.

    Expected table columns include:
      volume_name, component_id, point_x, point_y, point_z, point_hu
    """
    if not txt_path.exists():
        raise FileNotFoundError(f"Anchor points TXT not found:\n{txt_path}")

    records: List[Dict] = []
    header = None

    with open(txt_path, "r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line:
                continue

            parts = line.split("\t")

            # Skip metadata lines.
            if len(parts) == 2 and parts[0] in {"case_id", "invalid_hu_value", "max_search_radius"}:
                continue

            if parts[0] == "volume_name":
                header = parts
                continue

            if header is None:
                continue

            if len(parts) != len(header):
                print(f"[WARNING] Skipping malformed TXT row: {line}")
                continue

            row = dict(zip(header, parts))

            try:
                row["component_id"] = int(row["component_id"])
                row["component_voxels"] = int(row["component_voxels"])
                row["centroid_x"] = float(row["centroid_x"])
                row["centroid_y"] = float(row["centroid_y"])
                row["centroid_z"] = float(row["centroid_z"])
                row["point_x"] = int(row["point_x"])
                row["point_y"] = int(row["point_y"])
                row["point_z"] = int(row["point_z"])
                row["point_hu"] = float(row["point_hu"])
                row["distance_to_centroid"] = float(row["distance_to_centroid"])
                row["found_radius"] = int(row["found_radius"])
            except Exception as e:
                print(f"[WARNING] Skipping row because parsing failed: {line}")
                print(f"[WARNING] Error: {e}")
                continue

            records.append(row)

    if len(records) == 0:
        raise RuntimeError(f"No valid anchor point records found in: {txt_path}")

    return records


def get_highest_z_anchor_point(anchor_txt_path: Path) -> np.ndarray:
    """
    Select the anchor point with the highest Z coordinate.

    Returns:
        np.ndarray([point_x, point_y, point_z], dtype=float64)
    """
    records = parse_anchor_points_txt(anchor_txt_path)

    selected = max(records, key=lambda r: r["point_z"])

    center = np.array(
        [selected["point_x"], selected["point_y"], selected["point_z"]],
        dtype=np.float64,
    )

    print("=" * 100)
    print("[DYNAMIC CENTER SELECTION]")
    print(f"[TXT] {anchor_txt_path}")
    print(f"[SELECTED VOLUME] {selected['volume_name']}")
    print(f"[SELECTED COMPONENT ID] {selected['component_id']}")
    print(f"[CENTER XYZ] {center.tolist()}")
    print(f"[POINT HU] {selected['point_hu']:.3f}")
    print("=" * 100)

    return center


# ============================================================
# 4. Immediate Neighbor Toward Center
# ============================================================
def get_immediate_neighbor_toward_center(coords: np.ndarray, center: np.ndarray) -> np.ndarray:
    """
    For each voxel coordinate, compute the first neighboring voxel entered by
    the ray from the current voxel center toward the specified center point.

    This neighbor can be a 6-neighbor, 18-neighbor, or 26-neighbor depending on
    which voxel boundary is crossed first.
    """
    coords_f = coords.astype(np.float64)

    direction = center[None, :] - coords_f
    sign = np.sign(direction).astype(np.int8)
    abs_dir = np.abs(direction)

    # Parametric distance from voxel center to each axis boundary.
    # Voxel center to boundary distance is 0.5 voxel.
    with np.errstate(divide="ignore", invalid="ignore"):
        t_to_boundary = 0.5 / abs_dir

    # If there is no movement along an axis, this axis is never crossed first.
    t_to_boundary[abs_dir == 0] = np.inf

    # Find the first crossed boundary.
    t_min = np.min(t_to_boundary, axis=1, keepdims=True)

    # If multiple axes are crossed simultaneously, the neighbor is diagonal.
    cross_axes = np.isclose(
        t_to_boundary,
        t_min,
        rtol=1e-7,
        atol=1e-12,
    )

    step = sign * cross_axes.astype(np.int8)
    neighbor_coords = coords + step

    return neighbor_coords


# ============================================================
# 5. Core Processing Function
# ============================================================
def find_inner_surface_toward_center(
    input_path: Path,
    output_path: Path,
    target_labels: list[int],
    center: np.ndarray,
) -> Path:
    print("=" * 100)
    print("[FIND DUODENUM INNER SURFACE TOWARD DYNAMIC CENTER]")
    print(f"[INPUT ] {input_path}")
    print(f"[OUTPUT] {output_path}")
    print(f"[LABELS] {target_labels}")
    print(f"[CENTER] {center.tolist()}")
    print("=" * 100)

    ensure_dir(output_path.parent)

    if SKIP_IF_FINAL_EXISTS and output_path.exists():
        print(f"[SKIP] Output already exists: {output_path}")
        return output_path

    print("[INFO] Loading AllSeg mask...")
    nii, data = load_nifti(input_path)

    target_mask = np.isin(data, target_labels)

    print(f"[INFO] Image shape: {target_mask.shape}")
    print(f"[INFO] Total target voxels: {int(np.sum(target_mask)):,}")

    target_coords = np.argwhere(target_mask)

    if len(target_coords) == 0:
        raise RuntimeError(
            f"No target voxels were found for labels: {target_labels}.\n"
            f"Input mask: {input_path}"
        )

    print("[INFO] Finding immediate neighbor toward dynamic center for each target voxel...")

    neighbor_coords = get_immediate_neighbor_toward_center(
        target_coords,
        center,
    )

    shape = np.array(target_mask.shape)

    valid = np.all(
        (neighbor_coords >= 0)
        & (neighbor_coords < shape[None, :]),
        axis=1,
    )

    neighbor_is_target = np.zeros(len(target_coords), dtype=bool)
    valid_neighbors = neighbor_coords[valid]

    neighbor_is_target[valid] = target_mask[
        valid_neighbors[:, 0],
        valid_neighbors[:, 1],
        valid_neighbors[:, 2],
    ]

    # Core definition:
    # If the immediate neighboring voxel toward the selected center is not target label,
    # the current voxel is considered an inner-surface voxel.
    is_inner_surface = ~neighbor_is_target
    inner_surface_coords = target_coords[is_inner_surface]

    print(f"[INFO] Detected inner-surface voxels: {len(inner_surface_coords):,}")

    output = np.zeros_like(data, dtype=np.uint16)

    if len(inner_surface_coords) > 0:
        output[
            inner_surface_coords[:, 0],
            inner_surface_coords[:, 1],
            inner_surface_coords[:, 2],
        ] = data[
            inner_surface_coords[:, 0],
            inner_surface_coords[:, 1],
            inner_surface_coords[:, 2],
        ].astype(np.uint16)

    header = nii.header.copy()
    header.set_data_dtype(np.uint16)

    out_nii = nib.Nifti1Image(
        output,
        affine=nii.affine,
        header=header,
    )

    nib.save(out_nii, str(output_path))

    if not output_path.exists():
        raise RuntimeError(f"Output was not created: {output_path}")

    print("[DONE] Finished.")
    print(f"[SAVED] {output_path}")
    print("=" * 100)

    return output_path


# ============================================================
# 6. Command-Line Interface for run.py
# ============================================================
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Find Segment_19 duodenum inner surface toward the highest-Z anchor point."
    )

    # Kept for compatibility with run.py.
    parser.add_argument(
        "--ct_path",
        required=True,
        help="CT path passed by run.py. Accepted for pipeline compatibility but not directly used.",
    )

    parser.add_argument(
        "--output_dir",
        required=True,
        help="Output directory passed by run.py. Accepted for pipeline compatibility.",
    )

    parser.add_argument(
        "--case_id",
        required=False,
        default=None,
        help="Case ID passed by run.py. If omitted, inferred from CT filename.",
    )

    return parser.parse_args()


# ============================================================
# 7. Main Entry Point
# ============================================================
def main() -> None:
    args = parse_args()

    ct_path = Path(args.ct_path).resolve()
    case_id = args.case_id.strip() if args.case_id else strip_nii_extension(ct_path.name)

    if not case_id:
        raise ValueError("case_id is empty.")

    input_path = build_allseg_path(case_id)
    anchor_txt_path = build_anchor_points_txt_path(case_id)
    output_path = build_output_path(case_id)

    dynamic_center = get_highest_z_anchor_point(anchor_txt_path)

    find_inner_surface_toward_center(
        input_path=input_path,
        output_path=output_path,
        target_labels=TARGET_LABELS,
        center=dynamic_center,
    )


if __name__ == "__main__":
    main()
