import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import nibabel as nib
import numpy as np
from scipy import ndimage


# ============================================================
# 1. Global Settings
# ============================================================
BASE_DIR = Path(r"C:\Users\User\Desktop\AbdVesselGen")
ROI_CT_ROOT = BASE_DIR / "ROI_CT"
ANCHOR_POINTS_ROOT = BASE_DIR / "AnchorPoints"

INVALID_HU_VALUE = -1024

# Connected component settings.
# 26-connectivity is preferred for small 3D candidate boxes.
CONNECTIVITY_STRUCTURE = np.ones((3, 3, 3), dtype=np.uint8)

# If centroid voxel is invalid, search within the same component first.
# If still invalid, search nearby around the centroid.
MAX_NEARBY_SEARCH_RADIUS = 30

# Sphere radius used to visualize the extracted starting points.
# radius=2 gives diameter=5 voxels.
POINT_SPHERE_RADIUS = 2

# If final outputs already exist, skip this step.
SKIP_IF_FINAL_EXISTS = True


# ============================================================
# 2. Task Definition
# ============================================================
@dataclass
class StartMaskTask:
    name: str
    input_suffix: str
    output_label_base: int


# I included all four standard masks generated by SearchStart_RenalA_RenalV.py.
# Your message listed renal_vein_Lt twice; this likely meant renal_artery_Lt.
TASKS = [
    StartMaskTask(
        name="renal_artery_Lt",
        input_suffix="renal_artery_Lt_start_restrict",
        output_label_base=100,
    ),
    StartMaskTask(
        name="renal_artery_Rt",
        input_suffix="renal_artery_Rt_start_restrict",
        output_label_base=200,
    ),
    StartMaskTask(
        name="renal_vein_Lt",
        input_suffix="renal_vein_Lt_start_restrict",
        output_label_base=300,
    ),
    StartMaskTask(
        name="renal_vein_Rt",
        input_suffix="renal_vein_Rt_start_restrict",
        output_label_base=400,
    ),
]


# ============================================================
# 3. Path Builders
# ============================================================
def build_roi_ct_path(case_id: str) -> Path:
    return ROI_CT_ROOT / f"{case_id}_ROI_CT.nii.gz"


def build_task_input_path(case_id: str, task: StartMaskTask) -> Path:
    return ANCHOR_POINTS_ROOT / f"{case_id}_{task.input_suffix}.nii.gz"


def build_output_points_path(case_id: str) -> Path:
    return ANCHOR_POINTS_ROOT / f"{case_id}_renal_start_points_from_restrict_masks.nii.gz"


def build_output_txt_path(case_id: str) -> Path:
    return ANCHOR_POINTS_ROOT / f"{case_id}_renal_start_points_from_restrict_masks.txt"


def build_output_summary_path(case_id: str) -> Path:
    return ANCHOR_POINTS_ROOT / f"{case_id}_renal_start_points_from_restrict_masks_summary.txt"


# ============================================================
# 4. Utility Functions
# ============================================================
def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def strip_nii_extension(filename: str) -> str:
    lower = filename.lower()
    if lower.endswith(".nii.gz"):
        return filename[:-7]
    if lower.endswith(".nii"):
        return filename[:-4]
    return Path(filename).stem


def load_nifti(path: Path):
    if not path.exists():
        raise FileNotFoundError(f"File not found:\n{path}")
    img = nib.load(str(path))
    data = img.get_fdata()
    return img, data


def check_same_shape(reference_name: str, reference_data: np.ndarray, target_name: str, target_data: np.ndarray) -> None:
    if reference_data.shape != target_data.shape:
        raise ValueError(
            f"Shape mismatch: {reference_name} shape {reference_data.shape} "
            f"!= {target_name} shape {target_data.shape}"
        )


def is_inside_shape(point: Tuple[int, int, int], shape: Tuple[int, int, int]) -> bool:
    x, y, z = point
    sx, sy, sz = shape
    return 0 <= x < sx and 0 <= y < sy and 0 <= z < sz


# ============================================================
# 5. Centroid and Valid-HU Point Selection
# ============================================================
def compute_component_centroid(component_coords: np.ndarray) -> np.ndarray:
    return component_coords.astype(np.float64).mean(axis=0)


def round_centroid_to_voxel(centroid: np.ndarray) -> Tuple[int, int, int]:
    rounded = np.rint(centroid).astype(np.int64)
    return tuple(int(v) for v in rounded.tolist())


def find_nearest_valid_voxel_inside_component(
    ct_data: np.ndarray,
    component_coords: np.ndarray,
    centroid: np.ndarray,
    invalid_hu_value: float = INVALID_HU_VALUE,
) -> Optional[Tuple[int, int, int]]:
    """
    Prefer a voxel inside the same connected component.
    Pick the component voxel closest to centroid, but require HU != -1024.
    If multiple voxels are similarly close, this naturally picks the closest one.
    """
    if component_coords.size == 0:
        return None

    hu_values = ct_data[
        component_coords[:, 0],
        component_coords[:, 1],
        component_coords[:, 2],
    ]

    valid_mask = hu_values != invalid_hu_value
    if not np.any(valid_mask):
        return None

    valid_coords = component_coords[valid_mask]
    distances = np.linalg.norm(valid_coords.astype(np.float64) - centroid[None, :], axis=1)
    best_idx = int(np.argmin(distances))
    best = valid_coords[best_idx]

    return tuple(int(v) for v in best.tolist())


def find_nearest_valid_voxel_near_centroid(
    ct_data: np.ndarray,
    centroid: np.ndarray,
    invalid_hu_value: float = INVALID_HU_VALUE,
    max_radius: int = MAX_NEARBY_SEARCH_RADIUS,
) -> Optional[Tuple[int, int, int]]:
    """
    Fallback search around the rounded centroid.
    This is used if the entire connected component overlaps invalid ROI_CT voxels.
    """
    shape = np.array(ct_data.shape, dtype=np.int64)
    center = np.rint(centroid).astype(np.int64)

    for radius in range(0, max_radius + 1):
        x_min = max(0, int(center[0]) - radius)
        x_max = min(int(shape[0]) - 1, int(center[0]) + radius)
        y_min = max(0, int(center[1]) - radius)
        y_max = min(int(shape[1]) - 1, int(center[1]) + radius)
        z_min = max(0, int(center[2]) - radius)
        z_max = min(int(shape[2]) - 1, int(center[2]) + radius)

        sub_ct = ct_data[x_min:x_max + 1, y_min:y_max + 1, z_min:z_max + 1]
        valid = sub_ct != invalid_hu_value

        if not np.any(valid):
            continue

        local_coords = np.argwhere(valid)
        global_coords = local_coords + np.array([x_min, y_min, z_min], dtype=np.int64)
        distances = np.linalg.norm(global_coords.astype(np.float64) - centroid[None, :], axis=1)
        best = global_coords[int(np.argmin(distances))]
        return tuple(int(v) for v in best.tolist())

    return None


def select_valid_start_point(
    ct_data: np.ndarray,
    component_coords: np.ndarray,
    centroid: np.ndarray,
) -> Tuple[Optional[Tuple[int, int, int]], str]:
    rounded = round_centroid_to_voxel(centroid)

    if is_inside_shape(rounded, ct_data.shape) and float(ct_data[rounded]) != INVALID_HU_VALUE:
        return rounded, "rounded_centroid"

    in_component = find_nearest_valid_voxel_inside_component(
        ct_data=ct_data,
        component_coords=component_coords,
        centroid=centroid,
        invalid_hu_value=INVALID_HU_VALUE,
    )
    if in_component is not None:
        return in_component, "nearest_valid_voxel_inside_component"

    nearby = find_nearest_valid_voxel_near_centroid(
        ct_data=ct_data,
        centroid=centroid,
        invalid_hu_value=INVALID_HU_VALUE,
        max_radius=MAX_NEARBY_SEARCH_RADIUS,
    )
    if nearby is not None:
        return nearby, "nearest_valid_voxel_near_centroid"

    return None, "failed_no_valid_hu_voxel"


# ============================================================
# 6. Drawing
# ============================================================
def draw_sphere(
    output: np.ndarray,
    center: Tuple[int, int, int],
    radius: int,
    label_value: int,
) -> None:
    cx, cy, cz = center
    shape = output.shape

    x_min = max(cx - radius, 0)
    x_max = min(cx + radius + 1, shape[0])
    y_min = max(cy - radius, 0)
    y_max = min(cy + radius + 1, shape[1])
    z_min = max(cz - radius, 0)
    z_max = min(cz + radius + 1, shape[2])

    xs = np.arange(x_min, x_max)
    ys = np.arange(y_min, y_max)
    zs = np.arange(z_min, z_max)
    xg, yg, zg = np.meshgrid(xs, ys, zs, indexing="ij")

    dist = np.sqrt((xg - cx) ** 2 + (yg - cy) ** 2 + (zg - cz) ** 2)
    sphere = dist <= radius

    output[x_min:x_max, y_min:y_max, z_min:z_max][sphere] = int(label_value)


# ============================================================
# 7. Core Processing
# ============================================================
def process_one_task(
    task: StartMaskTask,
    case_id: str,
    ct_data: np.ndarray,
    output_points: np.ndarray,
) -> List[Dict]:
    input_path = build_task_input_path(case_id, task)

    print("\n" + "=" * 100)
    print(f"[PROCESS TASK] {task.name}")
    print(f"[INPUT] {input_path}")
    print("=" * 100)

    mask_img, mask_data = load_nifti(input_path)
    check_same_shape("ROI_CT", ct_data, task.name, mask_data)

    binary_mask = mask_data > 0
    total_voxels = int(binary_mask.sum())

    print(f"[INFO] Positive voxels: {total_voxels:,}")

    if total_voxels == 0:
        print(f"[WARNING] Empty mask for task: {task.name}")
        return []

    labeled, num_components = ndimage.label(binary_mask, structure=CONNECTIVITY_STRUCTURE)
    print(f"[INFO] Connected components found: {num_components}")

    records: List[Dict] = []

    for component_id in range(1, num_components + 1):
        component_mask = labeled == component_id
        component_coords = np.argwhere(component_mask)
        component_voxels = int(component_coords.shape[0])

        centroid = compute_component_centroid(component_coords)
        rounded_centroid = round_centroid_to_voxel(centroid)

        start_point, selection_method = select_valid_start_point(
            ct_data=ct_data,
            component_coords=component_coords,
            centroid=centroid,
        )

        if start_point is None:
            print(
                f"[WARNING] {task.name} component {component_id}: "
                "no valid HU voxel found. Skipped."
            )
            records.append({
                "task_name": task.name,
                "component_id": component_id,
                "component_voxels": component_voxels,
                "centroid_x": float(centroid[0]),
                "centroid_y": float(centroid[1]),
                "centroid_z": float(centroid[2]),
                "rounded_x": rounded_centroid[0],
                "rounded_y": rounded_centroid[1],
                "rounded_z": rounded_centroid[2],
                "point_x": "NA",
                "point_y": "NA",
                "point_z": "NA",
                "point_hu": "NA",
                "output_label": 0,
                "selection_method": selection_method,
                "status": "failed",
            })
            continue

        point_hu = float(ct_data[start_point])
        output_label = int(task.output_label_base + component_id)

        draw_sphere(
            output=output_points,
            center=start_point,
            radius=POINT_SPHERE_RADIUS,
            label_value=output_label,
        )

        print(
            f"[OK] {task.name} component {component_id}: "
            f"voxels={component_voxels:,}, centroid={np.round(centroid, 2).tolist()}, "
            f"point={start_point}, HU={point_hu:.1f}, label={output_label}, method={selection_method}"
        )

        records.append({
            "task_name": task.name,
            "component_id": component_id,
            "component_voxels": component_voxels,
            "centroid_x": float(centroid[0]),
            "centroid_y": float(centroid[1]),
            "centroid_z": float(centroid[2]),
            "rounded_x": rounded_centroid[0],
            "rounded_y": rounded_centroid[1],
            "rounded_z": rounded_centroid[2],
            "point_x": start_point[0],
            "point_y": start_point[1],
            "point_z": start_point[2],
            "point_hu": point_hu,
            "output_label": output_label,
            "selection_method": selection_method,
            "status": "ok",
        })

    return records


def run_renal_start_extract(case_id: str) -> Tuple[Path, Path, Path]:
    ct_path = build_roi_ct_path(case_id)
    output_points_path = build_output_points_path(case_id)
    output_txt_path = build_output_txt_path(case_id)
    output_summary_path = build_output_summary_path(case_id)

    print("=" * 100)
    print("[RENAL START EXTRACT - RUN.PY VERSION]")
    print(f"[CASE ID] {case_id}")
    print(f"[ROI CT ] {ct_path}")
    print(f"[OUTPUT ] {output_points_path}")
    print(f"[TXT    ] {output_txt_path}")
    print(f"[SUMMARY] {output_summary_path}")
    print("=" * 100)

    ensure_dir(ANCHOR_POINTS_ROOT)

    if SKIP_IF_FINAL_EXISTS and output_points_path.exists() and output_txt_path.exists() and output_summary_path.exists():
        print(f"[SKIP] Output already exists: {output_points_path}")
        print(f"[SKIP] TXT already exists: {output_txt_path}")
        print(f"[SKIP] Summary already exists: {output_summary_path}")
        return output_points_path, output_txt_path, output_summary_path

    ct_img, ct_data = load_nifti(ct_path)
    print(f"[INFO] ROI CT shape: {ct_data.shape}")
    print(f"[INFO] ROI CT HU range: min={ct_data.min():.1f}, max={ct_data.max():.1f}")

    output_points = np.zeros(ct_data.shape, dtype=np.uint16)

    all_records: List[Dict] = []
    for task in TASKS:
        records = process_one_task(
            task=task,
            case_id=case_id,
            ct_data=ct_data,
            output_points=output_points,
        )
        all_records.extend(records)

    output_header = ct_img.header.copy()
    output_header.set_data_dtype(np.uint16)

    output_img = nib.Nifti1Image(
        output_points.astype(np.uint16),
        affine=ct_img.affine,
        header=output_header,
    )
    nib.save(output_img, str(output_points_path))

    if not output_points_path.exists():
        raise RuntimeError(f"Output was not created: {output_points_path}")

    # Full point table.
    txt_header = [
        "task_name",
        "component_id",
        "component_voxels",
        "centroid_x",
        "centroid_y",
        "centroid_z",
        "rounded_x",
        "rounded_y",
        "rounded_z",
        "point_x",
        "point_y",
        "point_z",
        "point_hu",
        "output_label",
        "selection_method",
        "status",
    ]

    with open(output_txt_path, "w", encoding="utf-8") as f:
        f.write("\t".join(txt_header) + "\n")
        for r in all_records:
            row = []
            for key in txt_header:
                value = r.get(key, "")
                if isinstance(value, float):
                    row.append(f"{value:.6f}")
                else:
                    row.append(str(value))
            f.write("\t".join(row) + "\n")

    # Compact summary.
    with open(output_summary_path, "w", encoding="utf-8") as f:
        f.write(f"case_id\t{case_id}\n")
        f.write(f"roi_ct_path\t{ct_path}\n")
        f.write(f"output_points_path\t{output_points_path}\n")
        f.write(f"output_txt_path\t{output_txt_path}\n")
        f.write(f"invalid_hu_value\t{INVALID_HU_VALUE}\n")
        f.write(f"point_sphere_radius\t{POINT_SPHERE_RADIUS}\n")
        f.write(f"max_nearby_search_radius\t{MAX_NEARBY_SEARCH_RADIUS}\n")
        f.write("\n")
        f.write("task_name\tinput_path\tcomponents_total\tpoints_ok\tpoints_failed\n")

        for task in TASKS:
            task_records = [r for r in all_records if r["task_name"] == task.name]
            ok = sum(1 for r in task_records if r["status"] == "ok")
            failed = sum(1 for r in task_records if r["status"] != "ok")
            f.write(
                f"{task.name}\t{build_task_input_path(case_id, task)}\t"
                f"{len(task_records)}\t{ok}\t{failed}\n"
            )

    print("\n" + "=" * 100)
    print("[DONE] Renal start extraction completed.")
    print(f"[OUTPUT POINTS] {output_points_path}")
    print(f"[OUTPUT TXT   ] {output_txt_path}")
    print(f"[SUMMARY      ] {output_summary_path}")
    print(f"[INFO] Output labels present: {[int(x) for x in np.unique(output_points) if x > 0]}")
    print("=" * 100)

    return output_points_path, output_txt_path, output_summary_path


# ============================================================
# 8. Command-Line Interface for run.py
# ============================================================
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract centroid start points from renal start restrict masks and validate against ROI_CT HU."
    )

    parser.add_argument(
        "--ct_path",
        required=True,
        help="CT path passed by run.py. Accepted for compatibility; this script uses ROI_CT output.",
    )

    parser.add_argument(
        "--output_dir",
        required=True,
        help="Output directory passed by run.py. Accepted for compatibility; output is written to AnchorPoints.",
    )

    parser.add_argument(
        "--case_id",
        required=False,
        default=None,
        help="Case ID passed by run.py. If omitted, inferred from CT filename.",
    )

    return parser.parse_args()


# ============================================================
# 9. Main Entry Point
# ============================================================
def main() -> None:
    args = parse_args()
    ct_path = Path(args.ct_path).resolve()

    case_id = args.case_id.strip() if args.case_id else strip_nii_extension(ct_path.name)
    if not case_id:
        raise ValueError("case_id is empty.")

    run_renal_start_extract(case_id=case_id)


if __name__ == "__main__":
    main()
